---
abstract: 'Chained and minimal ORM'
author:
  - 'Alessandro Ranellucci <aar@cpan.org>'
build_requires:
  DBD::SQLite: 1.29
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Lite
requires:
  Carp: 0
  Clone: 0
  DBIx::Connector: 0
  Data::Page: 0
  List::MoreUtils: 0
  SQL::Abstract::More: 0
resources:
  bugtracker: https://github.com/alexrj/DBIx-Lite/issues
  repository: git://github.com/alexrj/DBIx-Lite.git
version: 0.15
